[colors]
background = '#0a0c10'
foreground = '#f0f3f6'

cursor_bg = '#f0f3f6'
cursor_border = '#f0f3f6'
cursor_fg = '#0a0c10'

selection_bg = '#204670'
selection_fg = '#f0f3f6'

ansi = [
    '#7a828e',
    '#ff9492',
    '#26cd4d',
    '#f0b72f',
    '#71b7ff',
    '#cb9eff',
    '#39c5cf',
    '#d9dee3',
]
brights = [
    '#9ea7b3',
    '#ffb1af',
    '#4ae168',
    '#f7c843',
    '#91cbff',
    '#dbb7ff',
    '#56d4dd',
    '#ffffff',
]