# (Github Light) Colors for Wezterm

[colors]
background = '#ffffff'
foreground = '#1F2328'

cursor_bg = '#1F2328'
cursor_border = '#1F2328'
cursor_fg = '#ffffff'

selection_bg = '#bbdfff'
selection_fg = '#1F2328'

ansi = [
    '#24292f',
    '#cf222e',
    '#116329',
    '#4d2d00',
    '#0969da',
    '#8250df',
    '#1b7c83',
    '#6e7781',
]
brights = [
    '#57606a',
    '#a40e26',
    '#1a7f37',
    '#633c01',
    '#218bff',
    '#a475f9',
    '#3192aa',
    '#8c959f',
]