# (Github Dark Default) Colors for Wezterm

[colors]
background = '#0d1117'
foreground = '#e6edf3'

cursor_bg = '#e6edf3'
cursor_border = '#e6edf3'
cursor_fg = '#0d1117'

selection_bg = '#1e4273'
selection_fg = '#e6edf3'

ansi = [
    '#484f58',
    '#ff7b72',
    '#3fb950',
    '#d29922',
    '#58a6ff',
    '#bc8cff',
    '#39c5cf',
    '#b1bac4',
]
brights = [
    '#6e7681',
    '#ffa198',
    '#56d364',
    '#e3b341',
    '#79c0ff',
    '#d2a8ff',
    '#56d4dd',
    '#ffffff',
]