# (Github Light Colorblind) Colors for kitty

[colors]
background = '#ffffff'
foreground = '#1b1f24'

cursor_bg = '#24292f'
cursor_border = '#24292f'
cursor_fg = '#ffffff'

selection_bg = '#bbdfff'
selection_fg = '#1b1f24'

ansi = [
    '#24292f',
    '#b35900',
    '#0550ae',
    '#4d2d00',
    '#0969da',
    '#8250df',
    '#1b7c83',
    '#6e7781',
]
brights = [
    '#57606a',
    '#8a4600',
    '#0969da',
    '#633c01',
    '#218bff',
    '#a475f9',
    '#3192aa',
    '#8c959f',
]